import { MigrationInterface, QueryRunner, Table, TableIndex, TableForeignKey } from 'typeorm';

/**
 * Migration: Add SURGEON role and surgical_checklists table
 *
 * - Extends the Postgres `users_role_enum` (generated by TypeORM for the
 *   `users.role` column) with a new 'surgeon' value, so the RolesGuard-based
 *   RBAC check for pre-operative checklist completion (NURSE or SURGEON) can
 *   be backed by a real, persisted role rather than a fake/parallel check.
 * - Creates the `surgical_checklists` table used by the pre-operative
 *   checklist API (issue #632). Each surgical case has at most one checklist;
 *   `items` stores the individual checklist line items (label, completed,
 *   completedBy, completedAt) as JSON, and `completedBy`/`completedAt` at the
 *   row level record who/when completed the checklist as a whole (set once
 *   all items are complete).
 */
export class AddSurgeonRoleAndSurgicalChecklist1782560900000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    // Postgres does not support adding enum values inside a transaction in
    // older versions, but modern Postgres (>=12) allows it; IF NOT EXISTS
    // guards against re-running.
    await queryRunner.query(`
      ALTER TYPE users_role_enum
      ADD VALUE IF NOT EXISTS 'surgeon';
    `);

    await queryRunner.createTable(
      new Table({
        name: 'surgical_checklists',
        columns: [
          {
            name: 'id',
            type: 'uuid',
            isPrimary: true,
            default: 'uuid_generate_v4()',
          },
          {
            name: 'surgicalCaseId',
            type: 'uuid',
            isNullable: false,
          },
          {
            name: 'items',
            type: 'jsonb',
            isNullable: false,
            default: "'[]'",
          },
          {
            name: 'isComplete',
            type: 'boolean',
            default: false,
          },
          {
            name: 'completedBy',
            type: 'varchar',
            isNullable: true,
          },
          {
            name: 'completedAt',
            type: 'timestamp',
            isNullable: true,
          },
          {
            name: 'createdAt',
            type: 'timestamp',
            default: 'now()',
          },
          {
            name: 'updatedAt',
            type: 'timestamp',
            default: 'now()',
          },
        ],
      }),
      true,
    );

    await queryRunner.createIndex(
      'surgical_checklists',
      new TableIndex({
        name: 'IDX_surgical_checklists_surgicalCaseId',
        columnNames: ['surgicalCaseId'],
        isUnique: true,
      }),
    );

    await queryRunner.createForeignKey(
      'surgical_checklists',
      new TableForeignKey({
        name: 'FK_surgical_checklists_surgicalCase',
        columnNames: ['surgicalCaseId'],
        referencedTableName: 'surgical_cases',
        referencedColumnNames: ['id'],
        onDelete: 'CASCADE',
      }),
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropForeignKey('surgical_checklists', 'FK_surgical_checklists_surgicalCase');
    await queryRunner.dropIndex('surgical_checklists', 'IDX_surgical_checklists_surgicalCaseId');
    await queryRunner.dropTable('surgical_checklists', true);
    // Note: Postgres does not support removing enum values; a full type
    // recreation would be needed to revert the 'surgeon' role value.
  }
}
